# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=30, verbose_name='内容')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('status', models.IntegerField(default=0, verbose_name='完成状态')),
                ('edit_status', models.IntegerField(default=0, verbose_name='编辑状态')),
            ],
            options={
                'verbose_name': '事件内容',
            },
        ),
    ]
